apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.24.0 (4a2a0458)
  creationTimestamp: null
  labels:
    io.kompose.service: maria
  name: maria
spec:
  ports:
    - name: "13306"
      port: 13306
      targetPort: 3306
  selector:
    io.kompose.service: maria
status:
  loadBalancer: {}
