apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.24.0 (4a2a0458)
  creationTimestamp: null
  labels:
    io.kompose.service: web7-chess-validations
  name: web7-chess-validations
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: web7-chess-validations
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml
        kompose.version: 1.24.0 (4a2a0458)
      creationTimestamp: null
      labels:
        io.kompose.network/mynetwork: "true"
        io.kompose.service: web7-chess-validations
    spec:
      containers:
        - env:
            - name: ENV
              value: prod
          image: buckflago/web7_chess_validations:latest
          name: chess-validations
          ports:
            - containerPort: 4000
          resources: {}
      restartPolicy: Always
status: {}
