spring:
  application:
    name: chess
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  datasource:
    url: jdbc:mariadb://localhost:13306/chess
    password: root
    username: root

